[workspace]
name = "iota-ctf"
members = [
    "iota-ctf-challenge-1",
    "iota-ctf-challenge-2",
    "iota-ctf-challenge-3",
    "iota-ctf-challenge-4",
    "iota-ctf-challenge-5",
    "iota-ctf-challenge-6",
]

